version: 2.1

orbs:
  orb-tools: circleci/orb-tools@11

workflows:
  test-pack:
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - orb-tools/review
      - hold:
          type: approval # presents manual approval button in the UI
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - orb-tools/review

      # release dev version of orb, for testing & possible publishing.
      # orb will be published as dev:alpha and dev:${CIRCLE_SHA1:0:7}.
      - orb-tools/publish:
          circleci-token: ORB_PUBLISH_TOKEN
          context: Codecov Orb Context
          orb-name: codecov/codecov
          pub-type: dev
          vcs-type: << pipeline.project.type >>
          requires:
            - hold

      # trigger an integration workflow to test the
      # dev:${CIRCLE_SHA1:0:7} version of your orb
      - orb-tools/continue:
          pipeline-number: << pipeline.number >>
          vcs-type: << pipeline.project.type >>
          requires:
            - orb-tools/publish
