version: 2.1
orbs:
  codecov: codecov/codecov@dev:alpha
  node: circleci/node@5
  orb-tools: circleci/orb-tools@11
  python: circleci/python@2
  win: circleci/windows@4

filters: &filters
  tags:
    only: /.*/

executors:
  python:
    docker:
      - image: cimg/python:3.10
  node:
    docker:
      - image: cimg/node:current

jobs:
  test-backend:
    executor: python
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: |
          coverage run -m unittest discover
      - persist_to_workspace:
          root: .
          paths:
            - .coverage
  test-frontend:
    executor: node
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm test
      - persist_to_workspace:
          root: .
          paths:
            - coverage/coverage-final.json
  test-codecov-orb-alpine:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: |
          apk add coreutils curl git gnupg
          mkdir ~/.gnupg
          touch ~/.gnupg/trustedkeys.gpg
      - codecov/upload:
          flags: backend,alpine
      - codecov/upload:
          file: coverage/coverage-final.json
          flags: frontend,alpine
          xtra_args: -v -Z
      - codecov/upload:
          file: coverage/coverage-final.json
          flags: version,alpine
          version: v0.1.0_8880
  test-codecov-orb-linux:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: .
      - codecov/upload:
          flags: backend,linux
      - codecov/upload:
          file: coverage/coverage-final.json
          flags: frontend,linux
          xtra_args: -v -Z
      - codecov/upload:
          file: coverage/coverage-final.json
          flags: version,linux
          version: v0.1.0_8880
  test-codecov-orb-macos:
    macos:
      xcode: 11.4
    steps:
      - checkout
      - attach_workspace:
          at: .
      - codecov/upload:
          flags: backend,macos
      - codecov/upload:
          file: coverage/coverage-final.json
          flags: frontend,macos
          xtra_args: -v -Z
      - codecov/upload:
          file: coverage/coverage-final.json
          flags: version,macos
          version: v0.1.0_8880
  test-codecov-orb-windows:
    executor:
      name: win/default
      shell: bash.exe
    steps:
      - checkout
      - attach_workspace:
          at: .
      - codecov/upload:
          flags: backend,windows
      - codecov/upload:
          file: coverage/coverage-final.json
          flags: frontend,windows
          xtra_args: -v -Z
      - codecov/upload:
          file: coverage/coverage-final.json
          flags: version,windows
          version: v0.1.0_8880

workflows:
  integration-tests_deploy:
    jobs:
      - test-backend
          filters: *filters
      - test-frontend
          filters: *filters
      - test-codecov-orb-alpine:
          filters: *filters
          requires:
            - test-backend
            - test-frontend

      - test-codecov-orb-linux:
          filters: *filters
          requires:
            - test-backend
            - test-frontend

      - test-codecov-orb-macos:
          filters: *filters
          requires:
            - test-backend
            - test-frontend

      - test-codecov-orb-windows:
          filters: *filters
          requires:
            - test-backend
            - test-frontend

      - orb-tools/publish:
          circleci-token: ORB_PUBLISH_TOKEN
          context: Codecov Orb Context
          enable-pr-comment: false
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
          orb-name: codecov/codecov
          pub-type: production
          requires:
            - test-codecov-orb-alpine
            - test-codecov-orb-linux
            - test-codecov-orb-macos
            - test-codecov-orb-windows
          vcs-type: github
